### ISSUE TITLE
Running manually

### ISSUE THREAD

**Issue by jasii** [hurricanehrndz/container-templates#4]
@hurricanehrndz Hey thanks again for all your hard work. I'm having some trouble getting it working properly though. So I'm running your subsonic manually and it was working great.

Now with this beta it doesn't seem to want to either download the 6.0 beta when I create the container from the new image or it doesn't start.

This is the old command that works great for the older version:
docker create --net=host -v /var/appdata/subsonic:/subsonic -v /media/music:/music -v /media/downloads/Podcasts:/podcasts -e TZ=America/Los_Angeles --name=subsonic hurricane/docker-subsonic

and this is the newer command that I'm trying to run:
docker create --net=host -v /var/appdata/subsonic:/subsonic -v /media/music:/music -v /media/downloads/Podcasts:/podcasts -e TZ=America/Los_Angeles --name=subsonicbeta hurricane/subsonic

I've of course stopped the old subsonic container so that the ports don't conflict. I still get connection refused when running the beta container.

Am I doing something wrong?

**Comment by hurricanehrndz** [comment]
This is on unRAID right?

**Comment by jasii** [comment]
I don't use unraid. I'm just using docker manually installed on Ubuntu
server.

**Comment by hurricanehrndz** [comment]
Oh okay, issue is in the wrong place. It should have been opened in docker-containers. Anyhow, I will start looking at it. Thanks.

**Comment by hurricanehrndz** [comment]
Okay, so the issue was a permissions error. Previously the subsonic container ran with UID 99 and GID 100 by default. Now it runs with UID 1000 and GID 1000 by default. The container has been update so that it changes the permissions if it notices that they differ from default (APP_UID, and APP_GID). This will ensure that the web interface comes up appropriately. If you don't wish to use the default UID and GID for the subsonic and want to keep what you had previously ensure you use the appropriate environment variables. Please refer to the readme.

**Comment by hurricanehrndz** [comment]
PS this container is not just a beta container it will update to whatever is the latest release available from subsonic, hope that works for you.

**Comment by jasii** [comment]
Awesome! I like the auto update feature, I think you're the only one out there with a 6.0 beta auto-updating container now :+1:  So I added the environmental variables for the other UID and GID I was using previously and it worked great. 

I am having one problem though. There is a problem with the transcoder not transcoding FLAC files now. Not exactly sure if it is from the 6.0 beta. Would you be able to check that out?

Is there anyway I can donate to you or help you out? You've been really helpful and I really appreciate you spending all this time getting this working.

**Comment by hurricanehrndz** [comment]
Yeah I will look into it and also getting a patreon page or something.

**Comment by hurricanehrndz** [comment]
Okay, it should be fixed now. Its building. There is donate button on the readme of docker page and github. Thank you so much.
